# metacall.pyi
from typing import Literal, overload, List, Dict, Any

@overload
def metacall(func: str, a: int, b: int) -> int: ...
@overload
def metacall(func: str, a: List[int]) -> int: ...
@overload
def metacall(func: str, a: Dict[str, int]) -> int: ...
@overload
def metacall(func: Literal["add"], a: int, b: int) -> int: ...
@overload
def metacall(func: Literal["add_float_vec"], a: List[int]) -> int: ...
@overload
def metacall(func: Literal["add_map"], a: Dict[str, int]) -> int: ...
@overload
def metacall(func: Literal["new_string"], a: int) -> str: ...
@overload
def metacall(func: Literal["string_len"], a: str) -> int: ...
def metacall(func: str, *args: Any) -> Any: ...
